//========================================================================================
//  $File: //a3t/argon/branches/v1/1.0/dev/textLayout_core/src/flashx/textLayout/formats/TabStopFormatInc.as $
//  $DateTime: 2010/01/21 11:42:11 $
//  $Revision: #10 $
//  $Change: 737515 $
//  
//  ADOBE CONFIDENTIAL
//  
//  Copyright 2008 Adobe Systems Incorporated. All rights reserved.
// 
//  NOTICE:  All information contained herein is, and remains
//  the property of Adobe Systems Incorporated and its suppliers,
//  if any.  The intellectual and technical concepts contained
//  herein are proprietary to Adobe Systems Incorporated and its
//  suppliers, and are protected by trade secret or copyright law.
//  Dissemination of this information or reproduction of this material
//  is strictly forbidden unless prior written permission is obtained
//  from Adobe Systems Incorporated.
//  
//  WARNING: THIS FILE IS GENERATED BY A SCRIPT.  DO NOT EDIT
//  
//========================================================================================
		/**
		 * TabStopFormat:
		 * The position of the tab stop, in pixels, relative to the start of the line.
		 * <p>Legal values are numbers from 0 to 10000 and flashx.textLayout.formats.FormatValue.INHERIT.</p>
		 * <p>Default value is undefined indicating not set.</p>
		 * <p>If undefined during the cascade this property will have a value of 0.</p>
		 * @see FormatValue#INHERIT
		 * 
		 * @throws RangeError when set value is not within range for this property
		 * 
		 * @playerversion Flash 10
		 * @playerversion AIR 1.5
		 * @langversion 3.0
		 */
		public function get position():*
		{
			return _tabStopFormatValueHolder ? _tabStopFormatValueHolder.position : undefined;
		}
		public function set position(positionValue:*):void
		{
			writableTabStopFormatValueHolder().position = positionValue;
			tabStopFormatChanged();
		}

		/**
		 * TabStopFormat:
		 * The tab alignment for this tab stop. 
		 * <p>Legal values are flash.text.engine.TabAlignment.START, flash.text.engine.TabAlignment.CENTER, flash.text.engine.TabAlignment.END, flash.text.engine.TabAlignment.DECIMAL, flashx.textLayout.formats.FormatValue.INHERIT.</p>
		 * <p>Default value is undefined indicating not set.</p>
		 * <p>If undefined during the cascade this property will have a value of START.</p>
		 * @see FormatValue#INHERIT
		 * 
		 * @throws RangeError when set value is not within range for this property
		 * 
		 * @playerversion Flash 10
		 * @playerversion AIR 1.5
		 * @langversion 3.0
		 * @see flash.text.engine.TabAlignment
		 */
		public function get alignment():*
		{
			return _tabStopFormatValueHolder ? _tabStopFormatValueHolder.alignment : undefined;
		}
		public function set alignment(alignmentValue:*):void
		{
			writableTabStopFormatValueHolder().alignment = alignmentValue;
			tabStopFormatChanged();
		}

		/**
		 * TabStopFormat:
		 * The alignment token to be used if the alignment is DECIMAL.
		 * <p>Default value is undefined indicating not set.</p>
		 * <p>If undefined during the cascade this property will have a value of null.</p>
		 * 
		 * @throws RangeError when set value is not within range for this property
		 * 
		 * @playerversion Flash 10
		 * @playerversion AIR 1.5
		 * @langversion 3.0
		 */
		public function get decimalAlignmentToken():*
		{
			return _tabStopFormatValueHolder ? _tabStopFormatValueHolder.decimalAlignmentToken : undefined;
		}
		public function set decimalAlignmentToken(decimalAlignmentTokenValue:*):void
		{
			writableTabStopFormatValueHolder().decimalAlignmentToken = decimalAlignmentTokenValue;
			tabStopFormatChanged();
		}
